// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxngwihhyyptfbgpwjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eG5nd2loaHl5cHRmYmdwd2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjE3MzgsImV4cCI6MjA1OTkzNzczOH0.sOixSlDXUDw0J9p0Tr3vzY4zpk10lH47CUwHDfmTx5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);